# Generated by Django 5.2.14 on 2026-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/'),
        ),
    ]
